name: Build and Containerize

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Dependencies
      run: npm ci
      env:
        CI: true
    - name: Build
      run: npm run build
    - name: Build Container
      run: docker build -f Dockerfile -t viva-auth-service .
